### ISSUE TITLE
NullReferenceException when accessing repository

### ISSUE THREAD

**Issue by tkennedy13** [johnknoop/MongoRepository#18]
I'm having some trouble accessing the repositories once they are added to the DI container. 

If I iterate all the services, I see that there is an IRepository<Site> service exists with a transient lifetime, but when I attempt to use the repository, I get 

`System.NullReferenceException: 'Object reference not set to an instance of an object.'`

![image](https://user-images.githubusercontent.com/7343218/155749970-8828899a-bb5b-4ffd-a715-4091329d9113.png)

Here is my implementation:

     MongoRepository.Configure()
                   .Database( settings.SharedDatabaseName, db => db
                        .Map<Site>( "Sites", x => x
                             .WithIndex( site => site.Abbreviation, unique: true )
                        )
                   )
                   .DatabasePerTenant( settings.DatabaseName, db => db   
                   )
                   .Build();
    builder.Services.AddRepositories( new MongoClient( settings.ConnectionString + settings.SharedDatabaseName ) );

This is a Blazor server project running on .Net 6.

**Comment by johnknoop** [comment]
Hi @tkennedy13 

Can you give me the whole stack trace?

**Comment by tkennedy13** [comment]
Sure. 

So I've tried this a couple different ways. In my Blazor view, if I include 

  ```
  [Inject]
  public IRepository<Site> _siteRepository { get; set; }
```
As soon as I attempt to access the page I get:

```
   [2022-02-27T01:12:33.558Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at IServiceCollection JohnKnoop.MongoRepository.DotNetCoreDi.ServiceCollectionExtensions.AddRepositories(IServiceCollection services, IMongoClient mongoClient)+(IServiceProvider provider) => { }
   at object Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at object Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at TResult Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at object Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Func<ServiceProviderEngineScope, object> Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.RealizeService(ServiceCallSite callSite)+(ServiceProviderEngineScope scope) => { } [0]
   at object Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Action<IServiceProvider, IComponent> Microsoft.AspNetCore.Components.ComponentFactory.CreateInitializer(Type type)+Initialize(IServiceProvider serviceProvider, IComponent component)
   at void Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at IComponent Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at void Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(ref RenderTreeFrame frame, int parentComponentId)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(ref DiffContext diffContext, int frameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(ref DiffContext diffContext, int frameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(ref DiffContext diffContext, int newFrameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(ref DiffContext diffContext, int oldFrameIndex, int newFrameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(ref DiffContext diffContext, int oldFrameIndex, int newFrameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(ref DiffContext diffContext, int oldFrameIndex, int newFrameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(ref DiffContext diffContext, int oldFrameIndex, int newFrameIndex)
   at void Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(ref DiffContext diffContext, int oldStartIndex, int oldEndIndexExcl, int newStartIndex, int newEndIndexExcl)
   at RenderTreeDiff Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, int componentId, ArrayRange<RenderTreeFrame> oldTree, ArrayRange<RenderTreeFrame> newTree)
   at void Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, out Exception renderFragmentException)
   at void Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() blazor.server.js:1:115531
```

I've also tried to access the repository in the Configure section and I get:
```

 at JohnKnoop.MongoRepository.DotNetCoreDi.ServiceCollectionExtensions.<>c__DisplayClass0_1.<AddRepositories>b__0(IServiceProvider provider)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
 at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
 at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
 at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
 at Program.<<Main>$>d__0.MoveNext() in C:\Users\...\Program.cs:line 139

```

**Comment by johnknoop** [comment]
Thanks, I'll have a look at it.

**Comment by johnknoop** [comment]
By the way: you have registered the `ResolveTenantKey` type, right?

Example:

```cs
services.AddScoped<ResolveTenantKey>(provider => () =>
{
  // return tenant key found in user claim or similar
});
```

Currently, the library requires this, even if you don't use multi-tenancy.

**Comment by tkennedy13** [comment]
Hmm, no, I didn't see that mentioned in the doc.  I've tried to register that, but I can't figure out what goes in the brackets. Do you have a simple example? 

Eventually l will return a value from the user's claim.

**Comment by johnknoop** [comment]
You can get from a user claim like this:

```cs
services.AddScoped<ResolveTenantKey>(provider => () =>
{
  var httpContextAccessor = provider.GetService<IHttpContextAccessor>();
  var user = httpContextAccessor.HttpContext?.User as ClaimsIdentity;

  var tenantKey = user?.Identity.Claims.SingleOrDefault(x => x.Type == "TenantKey")?.Value;

  if (tenantKey == null)
  {
    // Redirect to login
  }

  return tenantKey;
});
```

**Comment by johnknoop** [comment]
Btw thanks for alerting me to the fact that this was missing from the docs. I've now updated the [readme in that repo](https://github.com/johnknoop/MongoRepository.DotNetCoreDi#configuration).

**Comment by tkennedy13** [comment]
Thanks for your help @johnknoop. Adding ResolveTenantKey as shown above, solved the issue.
